### PR TITLE
[RHPAM-2217] - Removing logging import to keep the script cross compa…

### PR DESCRIPTION
**Pull request by ricardozanini**
…tible with non-EAP images

See:
https://issues.jboss.org/browse/RHPAM-2217

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[KIECLOUD-XYZ] Subject`, `[RHDM-XYZ] Subject` or `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by spolti** [comment]
I don't remember all the places this common script is used, but, removing this line wouldn't cause issues on another images?

**Comment by ricardozanini** [comment]
> I don't remember all the places this common script is used, but, removing this line wouldn't cause issues on another images?

No, I added it simply as a best practice to have the functions used by the script in the import, not assumed.

It's assumed now because the import path in the smartrouter differ from the eap modules. :/

**Comment by errantepiphany** [comment]
> > I don't remember all the places this common script is used, but, removing this line wouldn't cause issues on another images?
> 
> No, I added it simply as a best practice to have the functions used by the script in the import, not assumed.
> 
> It's assumed now because the import path in the smartrouter differ from the eap modules. :/

@ricardozanini  I think it would be a good idea to look at all our scripts that source the common script, and make sure that they first source the logging script themselves. Just to be safe.

**Comment by ricardozanini** [comment]
Yeah I did that :stuck_out_tongue:

**Pull request merged**
