### PR TITLE
[RHDM-894][RHPAM-2016] Update RHDM and RHPAM images to use RHEL8 (UBI) base layer

### PR DESCRIPTION
**Pull request by errantepiphany**
[RHDM-894] Update RHDM images to use RHEL8 (UBI) base layer
https://issues.jboss.org/browse/RHDM-894

[RHPAM-2016] Update RHPAM images to use RHEL8 (UBI) base layer
https://issues.jboss.org/browse/RHPAM-2016

Signed-off-by: David Ward <dward@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[KIECLOUD-XYZ] Subject`, `[RHDM-XYZ] Subject` or `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by spolti** [comment]
Approved but, my my only concern is about the jdbc driver versions to make sure the versions that we are adding to the images are in the matrix support.

**Comment by errantepiphany** [comment]
@spolti I don't think the particular versions of the postgresql and mariadb jdbc drivers would be included in the official UBI8 channels if they weren't supported themselves. However regarding the support "matrix" (I'm assuming you mean those drivers with EAP 7.2.1), we'd have to see...

**Comment by errantepiphany** [comment]
@spolti Update: Ken pointed me here, so it looks like they are in the support matrix:
"JBoss EAP 7.2 Tested Integrations"
https://access.redhat.com/articles/2026253

**Comment by errantepiphany** [comment]
@spolti One more concern, though...
Do we need to worry about any relationship between these DB changes, and rhpam-7-openshift-image/templates/contrib/jdbc ?

**Comment by spolti** [comment]
> @spolti One more concern, though...
> Do we need to worry about any relationship between these DB changes, and rhpam-7-openshift-image/templates/contrib/jdbc ?

I don't think so as for now we can use custom driver names for ejb timer.

**Pull request merged**
