### PR TITLE
[KIECLOUD-96] Enable KieServer OpenShiftStartupStrategy and Workbench…

### PR DESCRIPTION
**Pull request by rhtevan**
[JBPM-7834] Provide OpenShiftStartupStrategy - Enhancements related to RHPAM templates and others

Description
---
Setting new system properties and associated environment variables required for Workbench OpenShift enhancement.

Related JIRAs
https://issues.jboss.org/browse/KIECLOUD-96
https://issues.jboss.org/browse/JBPM-7834
https://issues.jboss.org/browse/BAPL-1090

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [x] Pull Request title is properly formatted: `[RHDM-XYZ] Subject` or `[RHPAM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted
- [x] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by rhtevan** [comment]
@errantepiphany @spolti 
Could you review this PR! 

Thanks, Evan

**Comment by errantepiphany** [comment]
@ryanzhang I think @spolti was just giving you an example. Although, perhaps we should include the other startup strategies in https://github.com/jboss-container-images/rhdm-7-openshift-image/blob/master/kieserver/image.yaml#L90 ? Also, why is it "LocalContainers..." (plural) instead of "LocalContainer..." (singular)?

Anyways, I think these are the droids you are looking for:
https://github.com/jboss-container-images/rhdm-7-openshift-image/blob/master/decisioncentral/image.yaml
https://github.com/jboss-container-images/rhpam-7-openshift-image/blob/master/businesscentral/image.yaml
https://github.com/jboss-container-images/jboss-kie-modules/blob/master/tests/features/common/kie-workbench-common.feature
https://github.com/jboss-container-images/jboss-kie-modules/blob/master/tests/features/rhdm/decisioncentral/rhdm-decisioncentral.feature
https://github.com/jboss-container-images/jboss-kie-modules/blob/master/tests/features/rhpam/businesscentral/rhpam-businesscentral.feature

And if this is also applicable to monitoring:
https://github.com/jboss-container-images/rhpam-7-openshift-image/blob/master/businesscentral-monitoring/image.yaml
https://github.com/jboss-container-images/jboss-kie-modules/blob/master/tests/features/rhpam/businesscentral-monitoring/rhpam-businesscentral-monitoring.feature

**Comment by rhtevan** [comment]
@errantepiphany Thanks! It's much clear to me know. BTW, you may accidentally tagged wrong person (I'm not Ryan). 

In term of applicable values for KIE_SERVER_STARTUP_STRATEGY,  it is dictated by the name of actual implementation class. To make a change will require refactoring the class name.
https://github.com/rhtevan/droolsjbpm-integration/blob/a993dc6f360c51f242b146c62b3a0cbca2096cf4/kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/StartupStrategyProvider.java#L43 

For example,
- https://github.com/rhtevan/droolsjbpm-integration/blob/a993dc6f360c51f242b146c62b3a0cbca2096cf4/kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/LocalContainersStartupStrategy.java#L37
- https://github.com/rhtevan/droolsjbpm-integration/blob/a993dc6f360c51f242b146c62b3a0cbca2096cf4/kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/ControllerBasedStartupStrategy.java#L38

IMHO, singular naming make sense here as plural named class is typical utility and helper classes with static methods.

**Comment by errantepiphany** [comment]
@rhtevan Evan, sorry about the mistag. Yup, I know that it has to match the class name. I was just airing my thoughts on the name choice, LOL.

**Comment by rhtevan** [comment]
@errantepiphany PR updated with requested changes. 
- https://github.com/rhtevan/jboss-kie-modules/blob/3ade3f1392c9ff65120a018c4b36c68844fbde20/tests/features/rhpam/businesscentral-monitoring/rhpam-businesscentral-monitoring.feature#L53-L62
- https://github.com/rhtevan/jboss-kie-modules/blob/3ade3f1392c9ff65120a018c4b36c68844fbde20/tests/features/rhpam/businesscentral/rhpam-businesscentral.feature#L53-L62
- https://github.com/rhtevan/jboss-kie-modules/blob/3ade3f1392c9ff65120a018c4b36c68844fbde20/tests/features/rhpam/kieserver/rhpam-kieserver.feature#L28-L39
- https://github.com/rhtevan/rhpam-7-openshift-image/blob/f845e3cf8b2b06266d4ab2e52b98a8a80a737a7c/businesscentral-monitoring/image.yaml#L51-L61
- https://github.com/rhtevan/rhpam-7-openshift-image/blob/f845e3cf8b2b06266d4ab2e52b98a8a80a737a7c/businesscentral/image.yaml#L96-L106
- https://github.com/rhtevan/rhpam-7-openshift-image/blob/f845e3cf8b2b06266d4ab2e52b98a8a80a737a7c/kieserver/image.yaml#L91-L93

**Comment by rhtevan** [comment]
@spolti @errantepiphany Could you give a check, see if it is ready to merge. Thanks!

**Comment by rhtevan** [comment]
@errantepiphany @spolti 
Great collaboration! Appreciated!

**Pull request merged**
