### PR TITLE
[KIECLOUD-294] Business Central [Settings]->[SSH Keys] doesn't persist

### PR DESCRIPTION
**Pull request by errantepiphany**
[KIECLOUD-294] Business Central [Settings]->[SSH Keys] doesn't persist
https://issues.jboss.org/browse/KIECLOUD-294

Signed-off-by: David Ward <dward@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[KIECLOUD-XYZ] Subject`, `[RHDM-XYZ] Subject` or `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by sutaakar** [comment]
@errantepiphany Can you please add some test coverage?

**Comment by errantepiphany** [comment]
I've tested it live in my environment, but sure, I can do that. I didn't originally since it's dead-simple.

**Comment by sutaakar** [comment]
It is not used just to test the functionality, it is used also as a regression check. In case there will be any refactoring in future or someone will delete this as unused code there should be something to hint purpose of these lines.

**Comment by spolti** [comment]
I agree with Karel, a simple bats test would be enough IMHO.

**Comment by errantepiphany** [comment]
@spolti @sutaakar Test added.

**Pull request merged**
